config/routes.rb
Health::Application.routes.draw do
  resources :price_ranges

  get "register", to: 'provider#index'
  get "login", to: 'provider#login'
  post 'login', to: 'provider#login'
  get 'success', to: 'provider#success'
  get "provider/search"
  get 'regions_select', to: 'welcome#regions'
  get 'provider_profile', to: 'provider#profile'
  get 'logout', to: 'provider#logout'

  post 'search_buy', to: 'welcome#search'

  resources :profiles

  resources :eusers

  get "practice-search", to: 'search#index'
  get "search", to: 'search#search'
  resources :practices

  resources :mm_ranges

  resources :confidential_infos

  resources :qualified_infos

  resources :public_informations

  resources :public_infos

  resources :regions

  resources :states

  resources :listings

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions" }

   root 'welcome#index'

end

app/models/confidential_info.rb
class ConfidentialInfo < ActiveRecord::Base
end

app/models/euser.rb
class Euser < ActiveRecord::Base
end

app/models/listing.rb
class Listing < ActiveRecord::Base
end

app/models/mm_range.rb
class MmRange < ActiveRecord::Base
end

app/models/practice.rb
class Practice < ActiveRecord::Base
end

app/models/price_range.rb
class PriceRange < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  	validates :email, presence: true, 
                    format: { with: VALID_EMAIL_REGEX }, 
                    uniqueness: { case_sensitive: false }
end

app/models/public_info.rb
class PublicInfo < ActiveRecord::Base
end

app/models/qualified_info.rb
class QualifiedInfo < ActiveRecord::Base
end

app/models/region.rb
class Region < ActiveRecord::Base
<<<<<<< HEAD
=======
  has_many :states
>>>>>>> cd54d6534d3e6666b63d418105e9d90ba912843b
end

app/models/state.rb
class State < ActiveRecord::Base
<<<<<<< HEAD
=======
  has_many :regions
>>>>>>> cd54d6534d3e6666b63d418105e9d90ba912843b
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable 
  
  attr_accessor :full_name
  attr_accessor :terms
  
  
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  layout 'admin'
  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id
    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render action: 'show', status: :created, location: @listing }
      else
        format.html { render action: 'new' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    @listing.user_id = current_user.id
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:state, :region, :type_of_practice, :average_annual_collections, :average_annual_visits, :street_address, :city, :state, :zip, :phone, :email, :low, :high, :user_id)
    end
end

app/helpers/eusers_helper.rb
module EusersHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/mm_ranges_helper.rb
module MmRangesHelper
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/provider_helper.rb
module ProviderHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :region %><br>
    <%= f.text_field :region %>
  </div>
  <div class="field">
    <%= f.label :type_of_practice %><br>
    <%= f.text_field :type_of_practice %>
  </div>
  <div class="field">
    <%= f.label :average_annual_collections %><br>
    <%= f.text_field :average_annual_collections %>
  </div>
  <div class="field">
    <%= f.label :average_annual_visits %><br>
    <%= f.number_field :average_annual_visits %>
  </div>
  <div class="field">
    <%= f.label :street_address %><br>
    <%= f.text_field :street_address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :low %><br>
    <%= f.text_field :low %>
  </div>
  <div class="field">
    <%= f.label :high %><br>
    <%= f.text_field :high %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<h1>Listing listings</h1>

<table>
  <thead>
    <tr>
      <th>State</th>
      <th>Region</th>
      <th>Type of practice</th>
      <th>Average annual collections</th>
      <th>Average annual visits</th>
      <th>Street address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Low</th>
      <th>High</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.state %></td>
        <td><%= listing.region %></td>
        <td><%= listing.type_of_practice %></td>
        <td><%= listing.average_annual_collections %></td>
        <td><%= listing.average_annual_visits %></td>
        <td><%= listing.street_address %></td>
        <td><%= listing.city %></td>
        <td><%= listing.state %></td>
        <td><%= listing.zip %></td>
        <td><%= listing.phone %></td>
        <td><%= listing.email %></td>
        <td><%= listing.low %></td>
        <td><%= listing.high %></td>
        <td><%= listing.user_id %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>State:</strong>
  <%= @listing.state %>
</p>

<p>
  <strong>Region:</strong>
  <%= @listing.region %>
</p>

<p>
  <strong>Type of practice:</strong>
  <%= @listing.type_of_practice %>
</p>

<p>
  <strong>Average annual collections:</strong>
  <%= @listing.average_annual_collections %>
</p>

<p>
  <strong>Average annual visits:</strong>
  <%= @listing.average_annual_visits %>
</p>

<p>
  <strong>Street address:</strong>
  <%= @listing.street_address %>
</p>

<p>
  <strong>City:</strong>
  <%= @listing.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @listing.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @listing.zip %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @listing.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @listing.email %>
</p>

<p>
  <strong>Low:</strong>
  <%= @listing.low %>
</p>

<p>
  <strong>High:</strong>
  <%= @listing.high %>
</p>

<p>
  <strong>User:</strong>
  <%= @listing.user_id %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>