config/routes.rb
Health::Application.routes.draw do
  resources :price_ranges

  get "register", to: 'provider#index'
  get "login", to: 'provider#login'
  post 'login', to: 'provider#login'
  get 'success', to: 'provider#success'
  get "provider/search"
  get 'regions_select', to: 'welcome#regions'
  get 'provider_profile', to: 'provider#profile'
  get 'logout', to: 'provider#logout'

  post 'search_buy', to: 'welcome#search'

  resources :profiles

  resources :eusers

  get "practice-search", to: 'search#index'
  get "search", to: 'search#search'
  resources :practices

  resources :mm_ranges

  resources :confidential_infos

  resources :qualified_infos

  resources :public_informations

  resources :public_infos

  resources :regions

  resources :states

  resources :listings

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions" }

   root 'welcome#index'

end

app/models/confidential_info.rb
class ConfidentialInfo < ActiveRecord::Base
end

app/models/euser.rb
class Euser < ActiveRecord::Base
end

app/models/listing.rb
class Listing < ActiveRecord::Base
end

app/models/mm_range.rb
class MmRange < ActiveRecord::Base
end

app/models/practice.rb
class Practice < ActiveRecord::Base
end

app/models/price_range.rb
class PriceRange < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  	validates :email, presence: true, 
                    format: { with: VALID_EMAIL_REGEX }, 
                    uniqueness: { case_sensitive: false }
end

app/models/public_info.rb
class PublicInfo < ActiveRecord::Base
end

app/models/qualified_info.rb
class QualifiedInfo < ActiveRecord::Base
end

app/models/region.rb
class Region < ActiveRecord::Base
<<<<<<< HEAD
=======
  has_many :states
>>>>>>> cd54d6534d3e6666b63d418105e9d90ba912843b
end

app/models/state.rb
class State < ActiveRecord::Base
<<<<<<< HEAD
=======
  has_many :regions
>>>>>>> cd54d6534d3e6666b63d418105e9d90ba912843b
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable 
  
  attr_accessor :full_name
  attr_accessor :terms
  
  
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  layout 'admin'
  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render action: 'show', status: :created, location: @state }
      else
        format.html { render action: 'new' }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name, :code)
    end
end

app/helpers/eusers_helper.rb
module EusersHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/mm_ranges_helper.rb
module MmRangesHelper
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/provider_helper.rb
module ProviderHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/states/_form.html.erb
<%= form_for(@state) do |f| %>
  <% if @state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% @state.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing state</h1>

<%= render 'form' %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<h1>Listing states</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.name %></td>
        <td><%= state.code %></td>
        <td><%= link_to 'Show', state %></td>
        <td><%= link_to 'Edit', edit_state_path(state) %></td>
        <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New State', new_state_path %>

app/views/states/new.html.erb
<h1>New state</h1>

<%= render 'form' %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @state.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @state.code %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>