config/routes.rb
Health::Application.routes.draw do
  resources :price_ranges

  get "register", to: 'provider#index'
  get "login", to: 'provider#login'
  post 'login', to: 'provider#login'
  get 'success', to: 'provider#success'
  get "provider/search"
  get 'regions_select', to: 'welcome#regions'
  get 'provider_profile', to: 'provider#profile'
  get 'logout', to: 'provider#logout'

  post 'search_buy', to: 'welcome#search'

  resources :profiles

  resources :eusers

  get "practice-search", to: 'search#index'
  get "search", to: 'search#search'
  resources :practices

  resources :mm_ranges

  resources :confidential_infos

  resources :qualified_infos

  resources :public_informations

  resources :public_infos

  resources :regions

  resources :states

  resources :listings

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions" }

   root 'welcome#index'

end

app/models/euser.rb
class Euser < ActiveRecord::Base
end

app/models/listing.rb
class Listing < ActiveRecord::Base
end

app/models/mm_range.rb
class MmRange < ActiveRecord::Base
end

app/models/practice.rb
class Practice < ActiveRecord::Base
end

app/models/price_range.rb
class PriceRange < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  	validates :email, presence: true, 
                    format: { with: VALID_EMAIL_REGEX }, 
                    uniqueness: { case_sensitive: false }
end

app/models/public_info.rb
class PublicInfo < ActiveRecord::Base
end

app/models/qualified_info.rb
class QualifiedInfo < ActiveRecord::Base
end

app/models/region.rb
class Region < ActiveRecord::Base
<<<<<<< HEAD
=======
  has_many :states
>>>>>>> cd54d6534d3e6666b63d418105e9d90ba912843b
end

app/models/state.rb
class State < ActiveRecord::Base
<<<<<<< HEAD
=======
  has_many :regions
>>>>>>> cd54d6534d3e6666b63d418105e9d90ba912843b
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable 
  
  attr_accessor :full_name
  attr_accessor :terms
  
  
end

app/controllers/public_infos_controller.rb
class PublicInfosController < ApplicationController
  before_action :set_public_info, only: [:show, :edit, :update, :destroy]

  layout 'admin'
  # GET /public_infos
  # GET /public_infos.json
  def index
    @public_infos = PublicInfo.all
  end

  # GET /public_infos/1
  # GET /public_infos/1.json
  def show
  end

  # GET /public_infos/new
  def new
    @public_info = PublicInfo.new
  end

  # GET /public_infos/1/edit
  def edit
  end

  # POST /public_infos
  # POST /public_infos.json
  def create
    @public_info = PublicInfo.new(public_info_params)

    respond_to do |format|
      if @public_info.save
        format.html { redirect_to @public_info, notice: 'Public info was successfully created.' }
        format.json { render action: 'show', status: :created, location: @public_info }
      else
        format.html { render action: 'new' }
        format.json { render json: @public_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /public_infos/1
  # PATCH/PUT /public_infos/1.json
  def update
    respond_to do |format|
      if @public_info.update(public_info_params)
        format.html { redirect_to @public_info, notice: 'Public info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @public_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /public_infos/1
  # DELETE /public_infos/1.json
  def destroy
    @public_info.destroy
    respond_to do |format|
      format.html { redirect_to public_infos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_public_info
      @public_info = PublicInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def public_info_params
      params.require(:public_info).permit(:practice_name, :avg_annual_collection, :avg_annual_visits)
    end
end

app/helpers/eusers_helper.rb
module EusersHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/mm_ranges_helper.rb
module MmRangesHelper
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/provider_helper.rb
module ProviderHelper
end

app/helpers/public_infos_helper.rb
module PublicInfosHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/public_infos/_form.html.erb
<%= form_for(@public_info) do |f| %>
  <% if @public_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@public_info.errors.count, "error") %> prohibited this public_info from being saved:</h2>

      <ul>
      <% @public_info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :practice_name %><br>
    <%= f.text_field :practice_name %>
  </div>
  <div class="field">
    <%= f.label :avg_annual_collection %><br>
    <%= f.text_field :avg_annual_collection %>
  </div>
  <div class="field">
    <%= f.label :avg_annual_visits %><br>
    <%= f.number_field :avg_annual_visits %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/public_infos/edit.html.erb
<h1>Editing public_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @public_info %> |
<%= link_to 'Back', public_infos_path %>

app/views/public_infos/index.html.erb
<h1>Listing public_infos</h1>

<table>
  <thead>
    <tr>
      <th>Practice name</th>
      <th>Avg annual collection</th>
      <th>Avg annual visits</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @public_infos.each do |public_info| %>
      <tr>
        <td><%= public_info.practice_name %></td>
        <td><%= public_info.avg_annual_collection %></td>
        <td><%= public_info.avg_annual_visits %></td>
        <td><%= link_to 'Show', public_info %></td>
        <td><%= link_to 'Edit', edit_public_info_path(public_info) %></td>
        <td><%= link_to 'Destroy', public_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Public info', new_public_info_path %>

app/views/public_infos/new.html.erb
<h1>New public_info</h1>

<%= render 'form' %>

<%= link_to 'Back', public_infos_path %>

app/views/public_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Practice name:</strong>
  <%= @public_info.practice_name %>
</p>

<p>
  <strong>Avg annual collection:</strong>
  <%= @public_info.avg_annual_collection %>
</p>

<p>
  <strong>Avg annual visits:</strong>
  <%= @public_info.avg_annual_visits %>
</p>

<%= link_to 'Edit', edit_public_info_path(@public_info) %> |
<%= link_to 'Back', public_infos_path %>